# - Try to find LibMicrohttpd
# Once done this will define
#  LIBMICROHTTPD_FOUND - System has LibMicrohttpd
#  LIBMICROHTTPD_VERSION - LibMicrohttpd version
#  LIBMICROHTTPD_DEFINITIONS - Compiler switches required for using LibMicrohttpd
#  LIBMICROHTTPD_INCLUDE_DIRS - The LibMicrohttpd include directories
#  LIBMICROHTTPD_LIBRARIES - The libraries needed to use LibMicrohttpd

find_package(PkgConfig)
pkg_check_modules(PC_LIBMICROHTTPD QUIET libmicrohttpd)

set(LIBMICROHTTPD_VERSION ${PC_LIBMICROHTTPD_VERSION})

set(LIBMICROHTTPD_DEFINITIONS ${PC_LIBMICROHTTPD_CFLAGS_OTHER})

find_path(
    LIBMICROHTTPD_INCLUDE_DIR microhttpd.h
    HINTS ${PC_LIBMICROHTTPD_INCLUDEDIR} ${PC_LIBMICROHTTPD_INCLUDE_DIRS})
set(LIBMICROHTTPD_INCLUDE_DIRS ${LIBMICROHTTPD_INCLUDE_DIR})

find_library(
    LIBMICROHTTPD_LIBRARY NAMES microhttpd
    HINTS ${PC_LIBMICROHTTPD_LIBDIR} ${PC_LIBMICROHTTPD_LIBRARY_DIRS})
set(LIBMICROHTTPD_LIBRARIES ${LIBMICROHTTPD_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LibMicrohttpd
    FOUND_VAR LIBMICROHTTPD_FOUND
    REQUIRED_VARS LIBMICROHTTPD_LIBRARY LIBMICROHTTPD_INCLUDE_DIR
    VERSION_VAR LIBMICROHTTPD_VERSION)
mark_as_advanced(LIBMICROHTTPD_INCLUDE_DIR LIBMICROHTTPD_LIBRARY)
